name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
    test: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
    
        - name: Install Node.js
          uses: actions/setup-node@v2
          with:
              node-version: '18'

        - run: npm ci
        - run: npm run test
        
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
      
            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '18'

            - name: Install dependencies
              run: npm ci
            
            - name: Build
              run: npm run build -- --prod --output-path docs
            
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.0
              with:
                branch: gh-pages
                folder: docs

