name: test-pull-request
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: write
  statuses: write

jobs:
  Test-and-get-coverage-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: See directory
        run: |
            ls -a
            pwd

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
            node-version: "18"

      - name: Install dependencies
        run: npm install
        working-directory: ./Web/CCMS


      - name: Run Jasmine tests
        run: npm run test -- --no-watch 
        working-directory: ./Web/CCMS
        continue-on-error: true

      - name: Comment Test Coverage
        uses: AthleticNet/comment-test-coverage@1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: Web/CCMS/coverage/ccms/coverage-summary.json
          title: Karma Test Coverage 2